Merge 1.17 into development
AtlasMediaGroup/TotalFreedomMod pull request #189
Opened 2022-01-17 21:03 UTC by Paldiu

2022-01-18 02:20 UTC, Focusvity requested changes
I don't know why the formatting has gone to Google-style; maybe reformat the project back to Allman style.

2022-01-18 02:20 UTC, Focusvity commented on src/main/java/me/totalfreedom/totalfreedommod/command/impl/SpawnMobCMD.java
> -import me.totalfreedom.totalfreedommod.config.ConfigEntry;
Please re-add the import

2022-01-24 09:12 UTC, Focusvity commented
Because we're no longer supporting Java 11 (by force), we should remove the workflow for Java 11 (as they will fail). @Paldiu @Wild1145 thoughts?

2022-02-05 23:06 UTC, Wild1145 commented
@Focusvity Once this has been merged we will disable the Java 11 build checks. I'm happy to override the merge on this occasion, however Codacy is un-happy with the code quality for this PR... That needs to be fixed as a matter of absolute urgency.

2022-02-05 23:13 UTC, Wild1145 requested changes
I've not got the entire way through, I'm also not sure why we've made such substantial changes to the way TFM is structured and refactored just about everything as part of a 1.17 upgrade, much less deployed it on to the server without a passing PR given the exceptionally poor code quality flags...

2022-02-05 23:13 UTC, Wild1145 commented on pom.xml
> +                            <outputDirectory>E:\A Folder for More Folders\Minecraft Servers\TotalFreedom Testing\plugins</outputDirectory>
This shouldn't have been added

2022-02-05 23:13 UTC, Wild1145 commented on pom.xml
> +                <version>3.3.1-SNAPSHOT</version>
We should not be using snapshot versions without there being a good reason, and that reason should be being documented here as a comment. (In the POM, Not Github comments)

2022-02-05 23:13 UTC, Wild1145 commented on pom.xml
> +    <pluginRepositories>
This should not be being added, we should either mirror via Nexus, or not be needing them. In this case again, Snapshots = Bad

2022-02-05 23:13 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/TotalFreedomMod.java
>              // Start bridges
We don't seem to tell the server to load these plugins prior to TFM, we should be doing it if we're going to intentionally not load up aspects of TFM based on them running / not.

2022-02-05 23:13 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/TotalFreedomMod.java
> +            essentialsBridge = new EssentialsBridge();
Why aren't these included in the if logic? Not sure having half of them enabled and half not is a good idea. Especially Libs & TFGuilds where they are not "Mandatory" plugins.

2022-02-05 23:19 UTC, Wild1145 commented
Out of my own boredom I've stopped manually cranking the Codacy output into this PR, please as a matter of critical urgency get these resolved as well as other review comments, and then we need to actually perform a proper code review.

2022-03-06 14:44 UTC, Wild1145 commented
This has been replaced by another PR currently also part of the 2022.02 release. Closing as declined.

2022-03-06 14:44 UTC, closed without merging