add ayunami2000 to dev list
AtlasMediaGroup/TotalFreedomMod pull request #218
Opened 2022-03-27 18:15 UTC by 1980s-housewife

2022-05-01 14:46 UTC, Wild1145 submitted a review, later dismissed

2022-06-05 21:57 UTC, Telesphoreo commented
This doesn't appear to compile and it's also based off of TFM 4.3 reloaded?...

2022-06-05 21:58 UTC, allinkdev commented on src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
>              "f97c0d7b-6413-4558-a409-88f09a8f9adb" // videogamesm12
Where is the comma?

2022-06-05 21:58 UTC, allinkdev requested changes

2022-06-05 21:58 UTC, allinkdev commented on src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
>              "f97c0d7b-6413-4558-a409-88f09a8f9adb" // videogamesm12
Where is the comma?

2022-06-05 21:59 UTC, allinkdev commented
> This doesn't appear to compile and it's also based off of TFM 4.3 reloaded?...

Doesn't seem to be an issue. It seems like the patch-4 branch was created by GitHub and has the same contents as the AtlasMediaGroup fork of TFM.

2022-06-08 23:20 UTC, Telesphoreo commented
I added you in #240 so this can be closed.

2022-06-08 23:20 UTC, closed without merging