Frontdoor and ban expiry only
AtlasMediaGroup/TotalFreedomMod pull request #27
Opened 2021-02-27 15:05 UTC by Paldiu

Correct PR; I will remove SQL fixes and then I will add the fix for the ban expiry division

2021-02-27 15:20 UTC, Wild1145 commented
@JeromSar - Could I ask you to review the FrontDoor part, as it has had some minor changes from the original version in order to have the functionality actually work with the servers setup.

2021-02-27 19:47 UTC, JeromSar approved these changes

2021-02-28 13:12 UTC, Wild1145 requested changes
As discussed can you remove the SQL Fix stuff from this PR. Then we'll merge just with front door.

2021-03-05 01:34 UTC, smartnt approved these changes

2021-03-05 01:37 UTC, merged