fixes of JIRA issues.
AtlasMediaGroup/TotalFreedomMod pull request #28
Opened 2021-02-28 17:26 UTC by abhiram555

Fixed FS-33 and FS-131

2021-03-01 17:52 UTC, Paldiu requested changes
Imagine submitting .idea files to the repo

2021-03-02 17:42 UTC, abhiram555 commented
Ready to merge?

2021-03-02 18:19 UTC, Paldiu submitted a review, later dismissed

2021-03-03 01:20 UTC, Paldiu approved these changes
Merge ready

2021-03-03 02:45 UTC, merged