Actually display assistant exec in game
AtlasMediaGroup/TotalFreedomMod pull request #37
Opened 2021-03-20 19:51 UTC by Elmon11

2021-03-20 23:53 UTC, Focusvity requested changes
While this is still pending, you might as well update to correct the spelling from ConfigEntry and other places that requires correction.

2021-03-21 12:47 UTC, Elmon11 commented
I'm not sure what you're referring to, what spelling errors?

2021-03-21 13:40 UTC, Wild1145 requested changes

2021-03-21 13:40 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/rank/RankManager.java
> +        if (ConfigEntry.SERVER_ASSTISTANT_EXECUTIVES.getList().contains(player.getName()) && plugin.al.isAdmin(player))
This line here, the config entry has assistant spelt incorrectly, the suggestion is to refactor it to be correctly spelt.

2021-03-21 14:20 UTC, Wild1145 submitted a review, later dismissed
Build failure in fUtil

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project TotalFreedomMod: Compilation failure

[ERROR] /home/travis/build/AtlasMediaGroup/TotalFreedomMod/src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java:[142,151] cannot find symbol

[ERROR]   symbol:   variable SERVER_ASSTISTANT_EXECUTIVES

[ERROR]   location: class me.totalfreedom.totalfreedommod.config.ConfigEntry

[ERROR] -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following 
```

2021-03-21 22:45 UTC, Focusvity approved these changes
I'm happy with the changes however the PR is on hold until we get FS-143 merged.

2021-04-04 12:24 UTC, merged