Create Command_seed.java
AtlasMediaGroup/TotalFreedomMod pull request #61
Opened 2021-05-08 19:29 UTC by Paldiu

2021-05-09 00:34 UTC, VideoGameSmash12 requested changes
quite a lot of problems

2021-05-09 00:34 UTC, VideoGameSmash12 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_seed.java
> +
missing permissions annotation, commands without these will cause the whole plugin to shit the bed

2021-05-09 00:34 UTC, VideoGameSmash12 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_seed.java
> +        player.sendMessage(String.valueOf(world.getSeed()));
why not just make the response look exactly like what it looks like in vanilla?

2021-05-09 00:34 UTC, VideoGameSmash12 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_seed.java
> +            sender.sendMessage("To check the world seed from console, you must provide a world name!");
this effectively removes functionality from the original command, probably should just get the overworld and use it as a fallback

2021-06-19 10:45 UTC, Focusvity commented
Closing due to inactivity

2021-06-19 10:45 UTC, closed without merging